# Data Sources

+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Dataset                                                                                        | Description                                                                                    | Link                                                                                                                                |
+================================================================================================+================================================================================================+=====================================================================================================================================+
| World Database on Protected Areas (WDPA)                                                       | Global database of protected areas with polygon and point data                                 | [protectedplanet.net](https://www.protectedplanet.net/en/thematic-areas/wdpa?tab=WDPA)                                              |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Biodiversity Hotspots Revisited, 2004                                                          | Biodiversity Hotspot polygons                                                                  | [databasin.org/datasets/e5e1b415498249d0b511b0eef8625c12/](https://databasin.org/datasets/e5e1b415498249d0b511b0eef8625c12/)        |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Last of the Wild Project, Version 2, 2005 (LWP-2): Last of the Wild Dataset (Geographic)       | Last of the Wild Project data, polygons of the 10% most wild areas of each biome of each realm | <https://www.earthdata.nasa.gov/data/catalog/sedac-ciesin-sedac-lwp2-hf-geog-2.00>                                                  |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Last of the Wild Project, Version 3 (LWP-3): 2009 Human Footprint, 2018 Release                | Raster of global human footprint                                                               | <https://www.earthdata.nasa.gov/data/catalog/sedac-ciesin-sedac-lwp3-hf-2009-2018.00>                                               |
|                                                                                                |                                                                                                |                                                                                                                                     |
|                                                                                                | Used as base to create world grid for analysis                                                 |                                                                                                                                     |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| *Matching Covariates*                                                                          |                                                                                                |                                                                                                                                     |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Last of the Wild Project, Version 2, 2005 (LWP-2): Global Human Footprint Dataset (Geographic) | Raster of global human footprint                                                               | <https://earthdata.nasa.gov/data/catalog/sedac-ciesin-sedac-lwp2-hf-geog-2.00>                                                      |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Agricultural potential                                                                         | Raster of global agricultural opportunity cost                                                 | [Naidoo & Iwamura, 2007](https://doi.org/10.1016/j.biocon.2007.07.025)                                                              |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Global Multi-resolution Terrain Elevation Data 2010, Mean Statistic, 30 arc-seconds            | Raster of global elevation                                                                     | [Global Multi-resolution Terrain Elevation Data - GMTED2010](https://topotools.cr.usgs.gov/gmted_viewer/gmted2010_global_grids.php) |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Global Rural-Urban Mapping Project, Version 1 (GRUMPv1): Population Density Grid               | Raster of global population density                                                            | <https://earthdata.nasa.gov/data/catalog/sedac-ciesin-sedac-grumpv1-popdens-1.00>                                                   |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Road Density                                                                                   | Raster of global road density used in creating global human footprint maps                     | <https://datadryad.org/stash/dataset/doi:10.5061/dryad.052q5>                                                                       |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Biome (from Terrestrial Ecoregions of the World)                                               | Broad classification of vegetation type across terrestrial areas globally                      | <https://www.worldwildlife.org/publications/terrestrial-ecoregions-of-the-world>                                                    |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Country                                                                                        | Administrative boundaries of countries across the world                                        | <https://databasin.org/datasets/e00ff45d152346658890f3e0f127b7b1/>                                                                  |
+------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
